using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using Teradyne.ARCM.RA.FailedTests.Models;
using Teradyne.ARCM.RA.FailedTests.DataFiles;
using Teradyne.ARCM.RA.FailedTests.AMPMessages;
using static Teradyne.ARCM.RA.FailedTests.AMPMessages.AMPMessageModel;
using System.Linq;

namespace Teradyne.ARCM.RA.FailedTests
{
    /// <summary>
    /// The purpose of this class is to process messages received from the testing environment.
    /// This is the main component responsible for 
    /// - parsing the details of the messages of interest
    /// - transforming the data
    /// - creating the data file
    /// </summary>
    internal class AMP_Messages_Processor
    {
        /// <summary>
        /// Description of the functions managing the messages according to their type
        /// </summary>
        /// <param name="origin">Requestor URL</param>
        /// <param name="raw">Raw AMP message</param>
        public delegate void AMP_Messages_Handler(string origin, AMPMessageModel raw);

        // Message names useful and analyzed by this DAS application

        /// <summary>
        /// SUBLOT_START message name
        /// </summary>
        public const string AMP_SUBLOT_START_Model_NAME = "SUBLOT_START";

        /// <summary>
        /// SUBLOT_END message name
        /// </summary>
        public const string AMP_SUBLOT_END_Model_NAME = "SUBLOT_END";

        /// <summary>
        /// TEST_START message name
        /// </summary>
        public const string AMP_TEST_START_Model_NAME = "TEST_START";
        
        /// <summary>
        /// TEST_END message name
        /// </summary>
        public const string AMP_TEST_END_Model_NAME = "TEST_END";

        /// <summary>
        /// TEST_DATA message name
        /// </summary>
        public const string AMP_TEST_DATA_Model_NAME = "TEST_DATA";

        /// <summary>
        /// Mapping between AMP message names and corresponding processing functions
        /// </summary>
        protected Dictionary<string, AMP_Messages_Handler> handlers;

        /// <summary>
        /// List of message names managed by this class.
        /// This is meant to be used to subscribe to the list of messages.
        /// </summary>
        public List<String> AMP_Message_Names { get { return handlers?.Keys.ToList<String>(); } }

        /// <summary>
        /// Output data file generated by this DAS.
        /// It contains the failed tests for each touchdown for the entire sublot
        /// </summary>
        protected FailedTestsDataFile datafile;

        /// <summary>
        /// Records all touchdowns for a sublot
        /// </summary>
        protected TouchdownsList currentSublot;

        /// <summary>
        /// Records all failed tests for a touchdown
        /// </summary>
        protected Touchdown currentTD;

        /// <summary>
        /// Message queue.
        /// Messages will be added by ScheduleMessageForProcessing and consumed by ProcessMessages.
        /// </summary>
        protected BlockingCollection<Tuple<string, AMPMessageModel>> messages;

        /// <summary>
        /// To allow stopping the message processing thread.
        /// </summary>
        private CancellationTokenSource _cancellation;

        /// <summary>
        /// Initialization
        /// </summary>
        public AMP_Messages_Processor()
        {
            setupHandlers();
            datafile = null;
            currentSublot = null;
            currentTD = null;
            messages = new BlockingCollection<Tuple<string, AMPMessageModel>>();
            _cancellation = new CancellationTokenSource();
        }

        /// <summary>
        /// Setting up the mapping between AMP message names and processing functions
        /// </summary>
        private void setupHandlers()
        {
            handlers = new Dictionary<string, AMP_Messages_Handler>()
            {
                { AMP_SUBLOT_START_Model_NAME, ProcessSubLotStart },
                { AMP_SUBLOT_END_Model_NAME, ProcessSubLotEnd },
                { AMP_TEST_START_Model_NAME, ProcessTestStart },
                { AMP_TEST_END_Model_NAME, ProcessTestEnd },
                { AMP_TEST_DATA_Model_NAME, ProcessTestData }
            };
        }

        /// <summary>
        /// Start the processing thread
        /// </summary>
        public void StartProcessing()
        {
            new Thread(() => ProcessMessages()).Start();
        }

        /// <summary>
        /// Stop the processing thread
        /// </summary>
        public void StopProcessing()
        {
            _cancellation.Cancel();
        }

        /// <summary>
        /// Extract the SUBLOT_ID from a message
        /// </summary>
        /// <param name="message">Message to parse</param>
        /// <returns>SUBLOT_ID obtained from the JSON message</returns>
        private string getSubLotIdFromMessage(AMPMessageModel message)
        {
            using (JsonDocument document = JsonDocument.Parse(message.Message))
            {
                JsonElement root = document.RootElement;
                JsonElement JsonSublotId;
                if (root.TryGetProperty("SUBLOT_ID", out JsonSublotId))
                    return JsonSublotId.GetString();
                else
                    return String.Empty;
            }
        }

        /// <summary>
        /// Initializes the handle to manage a new sublot.
        /// Configures the output data file.
        /// </summary>
        /// <param name="sublotid">Sublot ID obtained from the AMP message</param>
        protected void createNewSublot(string sublotid)
        {
            if (currentSublot != null) closeSublot(); // to be safe
            datafile = new FailedTestsDataFile(sublotid);
            currentSublot = new TouchdownsList();
            currentTD = null;
        }

        /// <summary>
        /// Processes the AMP SUBLOT_START message.
        /// Initializes lists of touchdowns and configures the output data file.
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        protected void ProcessSubLotStart(string origin, AMPMessageModel message)
        {
            // A sublot is started, so we create a new list of touchdowns.
            string sublotid = getSubLotIdFromMessage(message);
            createNewSublot(sublotid);
        }

        /// <summary>
        /// Save the data to the output file and reinitializes the variables
        /// </summary>
        protected void closeSublot()
        {
            if (currentSublot == null) return; // nothing to do

            datafile.saveToFile(currentSublot);
            currentTD = null;
            currentSublot = null;
            datafile = null;
        }

        /// <summary>
        /// Processes the AMP SUBLOT_END message.
        /// Save the data to the output file and reinitializes the variables
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        protected void ProcessSubLotEnd(string origin, AMPMessageModel message)
        {
            // A sublot ends, so we close the sublot by saving the data to a file
            closeSublot();
        }
        
        /// <summary>
        /// Processes the AMP TEST_START message.
        /// This is a new touchdown. Initializes the list holding the failed tests
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        protected void ProcessTestStart(string origin, AMPMessageModel message)
        {            
            if (currentSublot == null) ProcessSubLotStart(origin, message); // to be on the safe side. We could generate an error instead.

            // A test starts, so we create a new list of tests (represented by the Touchdown class)            
            currentTD = new Touchdown();
        }
        
        /// <summary>
        /// Processes the AMP TEST_END message.
        /// Records the list of failed tests and reinitializes the list for the next touchdown.
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        protected void ProcessTestEnd(string origin, AMPMessageModel message)
        {
            if (currentTD == null) return;
            if (currentSublot == null) return; // skipped as this should not happen. We could generate an error instead.

            currentSublot.touchdowns.Add(currentTD);
            currentTD = null;
        }

        /// <summary>
        /// Processes the AMP TEST_DATA message.
        /// This is where the data is filtered to only keep the failed tests.
        /// Each failed test is recorded and added to the current list.
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        protected void ProcessTestData(string origin, AMPMessageModel message)
        {
            try
            {
                if (currentSublot == null) return;  // Do nothing because this is not correct to have a TestData without Sublot Start
                if (currentTD == null) return; // Do nothing because this is not correct to have a TestData without Test Start

                // Let's parse the JSON document
                using (JsonDocument document = JsonDocument.Parse(message.Message))
                {
                    JsonElement root = document.RootElement;
                    JsonElement paramdata;
                    if (root.TryGetProperty("PARAMETRIC_DATA", out paramdata))
                    {
                        JsonElement JsonSector;
                        int? sector = null;
                        if (root.TryGetProperty("SECTOR", out JsonSector))
                            sector = JsonSector.GetInt32();

                        foreach (JsonElement elem in paramdata.EnumerateArray())
                        {
                            if (elem.GetProperty("PASS_FAIL").GetString() == "PASS") continue;

                            FailedParametricTestModel fptm = new FailedParametricTestModel();
                            fptm.Sector = sector;
                            fptm.Site = elem.GetProperty("SITE_NUM").GetInt32();
                            fptm.TestName = elem.GetProperty("TEST_NAME").GetString();
                            fptm.TestNumber = elem.GetProperty("TEST_NUMBER").GetInt32();
                            fptm.Measure = elem.GetProperty("RESULT").GetDouble();
                            fptm.LoLimit = elem.GetProperty("LO_LIM").GetDouble();
                            fptm.HiLimit = elem.GetProperty("HI_LIM").GetDouble();
                            fptm.ResScale = elem.GetProperty("RES_SCALE").GetInt32();
                            fptm.LoScale = elem.GetProperty("LLM_SCALE").GetInt32();
                            fptm.HiScale = elem.GetProperty("HLM_SCALE").GetInt32();

                            currentTD.failedTests.Add(fptm);
                        }
                    }

                    if (root.TryGetProperty("FUNCTIONAL_DATA", out paramdata))
                    {
                        JsonElement JsonSector;
                        int? sector = null;
                        if (root.TryGetProperty("SECTOR", out JsonSector))
                            sector = JsonSector.GetInt32();

                        foreach (JsonElement elem in paramdata.EnumerateArray())
                        {
                            if (elem.GetProperty("PASS_FAIL").GetString() == "PASS") continue;

                            FailedFunctionalTestModel fftm = new FailedFunctionalTestModel();
                            fftm.Sector = sector;
                            fftm.Site = elem.GetProperty("SITE_NUM").GetInt32();
                            fftm.TestName = elem.GetProperty("TEST_NAME").GetString();
                            fftm.TestNumber = elem.GetProperty("TEST_NUMBER").GetInt32();

                            currentTD.failedTests.Add(fftm);
                        }

                    }
                }
            }
            catch (Exception ex)
            {
                // Log error for debugging
                Console.WriteLine($"Error extracting timestamp: {ex.Message}");
            }

        }

        /// <summary>
        /// Main function processing the messages.
        /// It is meant to be executed in a thread.
        /// </summary>
        protected void ProcessMessages()
        {
            CancellationToken ct = _cancellation.Token;

            while (!ct.IsCancellationRequested)
            {
                Tuple<string, AMPMessageModel> item = messages.Take();
                AMPMessageModel message = item.Item2;
                handlers[message.MessageName](item.Item1, message);
            }
        }

        /// <summary>
        /// Enqueue new messages
        /// </summary>
        /// <param name="origin">Origin of the AMP message</param>
        /// <param name="message">AMP message</param>
        /// <returns>Success or failure</returns>
        internal bool ScheduleMessageForProcessing(string origin, AMPMessageModel message)
        {
            try
            {
                // no need to enqueue if we are not interested in the message
                if (!handlers.ContainsKey(message.MessageName)) return false;
                // enqueue for processing
                messages.Add(new Tuple<string, AMPMessageModel>(origin, message));                
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
